
services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    networks:
      - auction-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - auction-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge
